/*
Atricore Console :: Remote : API

# Atricore Console API

API version: 1.5.0-SNAPSHOT
Contact: sgonzalez@atricore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// StoreJossoRsReq struct for StoreJossoRsReq
type StoreJossoRsReq struct {
	IdaName *string `json:"idaName,omitempty"`
	Resource *JOSSO1ResourceDTO `json:"resource,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StoreJossoRsReq StoreJossoRsReq

// NewStoreJossoRsReq instantiates a new StoreJossoRsReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreJossoRsReq() *StoreJossoRsReq {
	this := StoreJossoRsReq{}
	return &this
}

// NewStoreJossoRsReqWithDefaults instantiates a new StoreJossoRsReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreJossoRsReqWithDefaults() *StoreJossoRsReq {
	this := StoreJossoRsReq{}
	return &this
}

// GetIdaName returns the IdaName field value if set, zero value otherwise.
func (o *StoreJossoRsReq) GetIdaName() string {
	if o == nil || isNil(o.IdaName) {
		var ret string
		return ret
	}
	return *o.IdaName
}

// GetIdaNameOk returns a tuple with the IdaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreJossoRsReq) GetIdaNameOk() (*string, bool) {
	if o == nil || isNil(o.IdaName) {
    return nil, false
	}
	return o.IdaName, true
}

// HasIdaName returns a boolean if a field has been set.
func (o *StoreJossoRsReq) HasIdaName() bool {
	if o != nil && !isNil(o.IdaName) {
		return true
	}

	return false
}

// SetIdaName gets a reference to the given string and assigns it to the IdaName field.
func (o *StoreJossoRsReq) SetIdaName(v string) {
	o.IdaName = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *StoreJossoRsReq) GetResource() JOSSO1ResourceDTO {
	if o == nil || isNil(o.Resource) {
		var ret JOSSO1ResourceDTO
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreJossoRsReq) GetResourceOk() (*JOSSO1ResourceDTO, bool) {
	if o == nil || isNil(o.Resource) {
    return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *StoreJossoRsReq) HasResource() bool {
	if o != nil && !isNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given JOSSO1ResourceDTO and assigns it to the Resource field.
func (o *StoreJossoRsReq) SetResource(v JOSSO1ResourceDTO) {
	o.Resource = &v
}

func (o StoreJossoRsReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.IdaName) {
		toSerialize["idaName"] = o.IdaName
	}
	if !isNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *StoreJossoRsReq) UnmarshalJSON(bytes []byte) (err error) {
	varStoreJossoRsReq := _StoreJossoRsReq{}

	if err = json.Unmarshal(bytes, &varStoreJossoRsReq); err == nil {
		*o = StoreJossoRsReq(varStoreJossoRsReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "idaName")
		delete(additionalProperties, "resource")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStoreJossoRsReq struct {
	value *StoreJossoRsReq
	isSet bool
}

func (v NullableStoreJossoRsReq) Get() *StoreJossoRsReq {
	return v.value
}

func (v *NullableStoreJossoRsReq) Set(val *StoreJossoRsReq) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreJossoRsReq) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreJossoRsReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreJossoRsReq(val *StoreJossoRsReq) *NullableStoreJossoRsReq {
	return &NullableStoreJossoRsReq{value: val, isSet: true}
}

func (v NullableStoreJossoRsReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreJossoRsReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


