/*
Atricore Console :: Remote : API

# Atricore Console API

API version: 1.5.0-SNAPSHOT
Contact: sgonzalez@atricore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// StoreIdSourceDbReq struct for StoreIdSourceDbReq
type StoreIdSourceDbReq struct {
	IdSourceDb *DbIdentitySourceDTO `json:"idSourceDb,omitempty"`
	IdSourceLdap *DbIdentitySourceDTO `json:"idSourceLdap,omitempty"`
	IdaName *string `json:"idaName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StoreIdSourceDbReq StoreIdSourceDbReq

// NewStoreIdSourceDbReq instantiates a new StoreIdSourceDbReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreIdSourceDbReq() *StoreIdSourceDbReq {
	this := StoreIdSourceDbReq{}
	return &this
}

// NewStoreIdSourceDbReqWithDefaults instantiates a new StoreIdSourceDbReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreIdSourceDbReqWithDefaults() *StoreIdSourceDbReq {
	this := StoreIdSourceDbReq{}
	return &this
}

// GetIdSourceDb returns the IdSourceDb field value if set, zero value otherwise.
func (o *StoreIdSourceDbReq) GetIdSourceDb() DbIdentitySourceDTO {
	if o == nil || o.IdSourceDb == nil {
		var ret DbIdentitySourceDTO
		return ret
	}
	return *o.IdSourceDb
}

// GetIdSourceDbOk returns a tuple with the IdSourceDb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreIdSourceDbReq) GetIdSourceDbOk() (*DbIdentitySourceDTO, bool) {
	if o == nil || o.IdSourceDb == nil {
		return nil, false
	}
	return o.IdSourceDb, true
}

// HasIdSourceDb returns a boolean if a field has been set.
func (o *StoreIdSourceDbReq) HasIdSourceDb() bool {
	if o != nil && o.IdSourceDb != nil {
		return true
	}

	return false
}

// SetIdSourceDb gets a reference to the given DbIdentitySourceDTO and assigns it to the IdSourceDb field.
func (o *StoreIdSourceDbReq) SetIdSourceDb(v DbIdentitySourceDTO) {
	o.IdSourceDb = &v
}

// GetIdSourceLdap returns the IdSourceLdap field value if set, zero value otherwise.
func (o *StoreIdSourceDbReq) GetIdSourceLdap() DbIdentitySourceDTO {
	if o == nil || o.IdSourceLdap == nil {
		var ret DbIdentitySourceDTO
		return ret
	}
	return *o.IdSourceLdap
}

// GetIdSourceLdapOk returns a tuple with the IdSourceLdap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreIdSourceDbReq) GetIdSourceLdapOk() (*DbIdentitySourceDTO, bool) {
	if o == nil || o.IdSourceLdap == nil {
		return nil, false
	}
	return o.IdSourceLdap, true
}

// HasIdSourceLdap returns a boolean if a field has been set.
func (o *StoreIdSourceDbReq) HasIdSourceLdap() bool {
	if o != nil && o.IdSourceLdap != nil {
		return true
	}

	return false
}

// SetIdSourceLdap gets a reference to the given DbIdentitySourceDTO and assigns it to the IdSourceLdap field.
func (o *StoreIdSourceDbReq) SetIdSourceLdap(v DbIdentitySourceDTO) {
	o.IdSourceLdap = &v
}

// GetIdaName returns the IdaName field value if set, zero value otherwise.
func (o *StoreIdSourceDbReq) GetIdaName() string {
	if o == nil || o.IdaName == nil {
		var ret string
		return ret
	}
	return *o.IdaName
}

// GetIdaNameOk returns a tuple with the IdaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreIdSourceDbReq) GetIdaNameOk() (*string, bool) {
	if o == nil || o.IdaName == nil {
		return nil, false
	}
	return o.IdaName, true
}

// HasIdaName returns a boolean if a field has been set.
func (o *StoreIdSourceDbReq) HasIdaName() bool {
	if o != nil && o.IdaName != nil {
		return true
	}

	return false
}

// SetIdaName gets a reference to the given string and assigns it to the IdaName field.
func (o *StoreIdSourceDbReq) SetIdaName(v string) {
	o.IdaName = &v
}

func (o StoreIdSourceDbReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IdSourceDb != nil {
		toSerialize["idSourceDb"] = o.IdSourceDb
	}
	if o.IdSourceLdap != nil {
		toSerialize["idSourceLdap"] = o.IdSourceLdap
	}
	if o.IdaName != nil {
		toSerialize["idaName"] = o.IdaName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *StoreIdSourceDbReq) UnmarshalJSON(bytes []byte) (err error) {
	varStoreIdSourceDbReq := _StoreIdSourceDbReq{}

	if err = json.Unmarshal(bytes, &varStoreIdSourceDbReq); err == nil {
		*o = StoreIdSourceDbReq(varStoreIdSourceDbReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "idSourceDb")
		delete(additionalProperties, "idSourceLdap")
		delete(additionalProperties, "idaName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStoreIdSourceDbReq struct {
	value *StoreIdSourceDbReq
	isSet bool
}

func (v NullableStoreIdSourceDbReq) Get() *StoreIdSourceDbReq {
	return v.value
}

func (v *NullableStoreIdSourceDbReq) Set(val *StoreIdSourceDbReq) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreIdSourceDbReq) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreIdSourceDbReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreIdSourceDbReq(val *StoreIdSourceDbReq) *NullableStoreIdSourceDbReq {
	return &NullableStoreIdSourceDbReq{value: val, isSet: true}
}

func (v NullableStoreIdSourceDbReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreIdSourceDbReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


