/*
Atricore Console :: Remote : API

# Atricore Console API

API version: 1.5.0-SNAPSHOT
Contact: sgonzalez@atricore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// GetExtSaml2SpReq struct for GetExtSaml2SpReq
type GetExtSaml2SpReq struct {
	IdaName *string `json:"idaName,omitempty"`
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetExtSaml2SpReq GetExtSaml2SpReq

// NewGetExtSaml2SpReq instantiates a new GetExtSaml2SpReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExtSaml2SpReq() *GetExtSaml2SpReq {
	this := GetExtSaml2SpReq{}
	return &this
}

// NewGetExtSaml2SpReqWithDefaults instantiates a new GetExtSaml2SpReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExtSaml2SpReqWithDefaults() *GetExtSaml2SpReq {
	this := GetExtSaml2SpReq{}
	return &this
}

// GetIdaName returns the IdaName field value if set, zero value otherwise.
func (o *GetExtSaml2SpReq) GetIdaName() string {
	if o == nil || isNil(o.IdaName) {
		var ret string
		return ret
	}
	return *o.IdaName
}

// GetIdaNameOk returns a tuple with the IdaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExtSaml2SpReq) GetIdaNameOk() (*string, bool) {
	if o == nil || isNil(o.IdaName) {
    return nil, false
	}
	return o.IdaName, true
}

// HasIdaName returns a boolean if a field has been set.
func (o *GetExtSaml2SpReq) HasIdaName() bool {
	if o != nil && !isNil(o.IdaName) {
		return true
	}

	return false
}

// SetIdaName gets a reference to the given string and assigns it to the IdaName field.
func (o *GetExtSaml2SpReq) SetIdaName(v string) {
	o.IdaName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetExtSaml2SpReq) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExtSaml2SpReq) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetExtSaml2SpReq) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetExtSaml2SpReq) SetName(v string) {
	o.Name = &v
}

func (o GetExtSaml2SpReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.IdaName) {
		toSerialize["idaName"] = o.IdaName
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *GetExtSaml2SpReq) UnmarshalJSON(bytes []byte) (err error) {
	varGetExtSaml2SpReq := _GetExtSaml2SpReq{}

	if err = json.Unmarshal(bytes, &varGetExtSaml2SpReq); err == nil {
		*o = GetExtSaml2SpReq(varGetExtSaml2SpReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "idaName")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetExtSaml2SpReq struct {
	value *GetExtSaml2SpReq
	isSet bool
}

func (v NullableGetExtSaml2SpReq) Get() *GetExtSaml2SpReq {
	return v.value
}

func (v *NullableGetExtSaml2SpReq) Set(val *GetExtSaml2SpReq) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExtSaml2SpReq) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExtSaml2SpReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExtSaml2SpReq(val *GetExtSaml2SpReq) *NullableGetExtSaml2SpReq {
	return &NullableGetExtSaml2SpReq{value: val, isSet: true}
}

func (v NullableGetExtSaml2SpReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExtSaml2SpReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


