/*
 * Atricore Console :: Remote : API
 *
 * # Atricore Console API
 *
 * API version: 1.4.3-SNAPSHOT
 * Contact: sgonzalez@atricore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// GetAppliancesReq struct for GetAppliancesReq
type GetAppliancesReq struct {
	IdaName *string `json:"idaName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAppliancesReq GetAppliancesReq

// NewGetAppliancesReq instantiates a new GetAppliancesReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppliancesReq() *GetAppliancesReq {
	this := GetAppliancesReq{}
	return &this
}

// NewGetAppliancesReqWithDefaults instantiates a new GetAppliancesReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppliancesReqWithDefaults() *GetAppliancesReq {
	this := GetAppliancesReq{}
	return &this
}

// GetIdaName returns the IdaName field value if set, zero value otherwise.
func (o *GetAppliancesReq) GetIdaName() string {
	if o == nil || o.IdaName == nil {
		var ret string
		return ret
	}
	return *o.IdaName
}

// GetIdaNameOk returns a tuple with the IdaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppliancesReq) GetIdaNameOk() (*string, bool) {
	if o == nil || o.IdaName == nil {
		return nil, false
	}
	return o.IdaName, true
}

// HasIdaName returns a boolean if a field has been set.
func (o *GetAppliancesReq) HasIdaName() bool {
	if o != nil && o.IdaName != nil {
		return true
	}

	return false
}

// SetIdaName gets a reference to the given string and assigns it to the IdaName field.
func (o *GetAppliancesReq) SetIdaName(v string) {
	o.IdaName = &v
}

func (o GetAppliancesReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IdaName != nil {
		toSerialize["idaName"] = o.IdaName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *GetAppliancesReq) UnmarshalJSON(bytes []byte) (err error) {
	varGetAppliancesReq := _GetAppliancesReq{}

	if err = json.Unmarshal(bytes, &varGetAppliancesReq); err == nil {
		*o = GetAppliancesReq(varGetAppliancesReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "idaName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAppliancesReq struct {
	value *GetAppliancesReq
	isSet bool
}

func (v NullableGetAppliancesReq) Get() *GetAppliancesReq {
	return v.value
}

func (v *NullableGetAppliancesReq) Set(val *GetAppliancesReq) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppliancesReq) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppliancesReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppliancesReq(val *GetAppliancesReq) *NullableGetAppliancesReq {
	return &NullableGetAppliancesReq{value: val, isSet: true}
}

func (v NullableGetAppliancesReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppliancesReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


