/*
Atricore Console :: Remote : API

# Atricore Console API

API version: 1.5.0-SNAPSHOT
Contact: sgonzalez@atricore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// GetBrandingRes struct for GetBrandingRes
type GetBrandingRes struct {
	BundleArtifact *string `json:"bundleArtifact,omitempty"`
	BundleGroup *string `json:"bundleGroup,omitempty"`
	BundleVersion *string `json:"bundleVersion,omitempty"`
	CustomOpenIdAppClazz *string `json:"customOpenIdAppClazz,omitempty"`
	CustomSsoAppClazz *string `json:"customSsoAppClazz,omitempty"`
	CustomSsoIdPAppClazz *string `json:"customSsoIdPAppClazz,omitempty"`
	Description *string `json:"description,omitempty"`
	Error *string `json:"error,omitempty"`
	Name *string `json:"name,omitempty"`
	Resource *string `json:"resource,omitempty"`
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetBrandingRes GetBrandingRes

// NewGetBrandingRes instantiates a new GetBrandingRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBrandingRes() *GetBrandingRes {
	this := GetBrandingRes{}
	return &this
}

// NewGetBrandingResWithDefaults instantiates a new GetBrandingRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBrandingResWithDefaults() *GetBrandingRes {
	this := GetBrandingRes{}
	return &this
}

// GetBundleArtifact returns the BundleArtifact field value if set, zero value otherwise.
func (o *GetBrandingRes) GetBundleArtifact() string {
	if o == nil || o.BundleArtifact == nil {
		var ret string
		return ret
	}
	return *o.BundleArtifact
}

// GetBundleArtifactOk returns a tuple with the BundleArtifact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetBundleArtifactOk() (*string, bool) {
	if o == nil || o.BundleArtifact == nil {
		return nil, false
	}
	return o.BundleArtifact, true
}

// HasBundleArtifact returns a boolean if a field has been set.
func (o *GetBrandingRes) HasBundleArtifact() bool {
	if o != nil && o.BundleArtifact != nil {
		return true
	}

	return false
}

// SetBundleArtifact gets a reference to the given string and assigns it to the BundleArtifact field.
func (o *GetBrandingRes) SetBundleArtifact(v string) {
	o.BundleArtifact = &v
}

// GetBundleGroup returns the BundleGroup field value if set, zero value otherwise.
func (o *GetBrandingRes) GetBundleGroup() string {
	if o == nil || o.BundleGroup == nil {
		var ret string
		return ret
	}
	return *o.BundleGroup
}

// GetBundleGroupOk returns a tuple with the BundleGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetBundleGroupOk() (*string, bool) {
	if o == nil || o.BundleGroup == nil {
		return nil, false
	}
	return o.BundleGroup, true
}

// HasBundleGroup returns a boolean if a field has been set.
func (o *GetBrandingRes) HasBundleGroup() bool {
	if o != nil && o.BundleGroup != nil {
		return true
	}

	return false
}

// SetBundleGroup gets a reference to the given string and assigns it to the BundleGroup field.
func (o *GetBrandingRes) SetBundleGroup(v string) {
	o.BundleGroup = &v
}

// GetBundleVersion returns the BundleVersion field value if set, zero value otherwise.
func (o *GetBrandingRes) GetBundleVersion() string {
	if o == nil || o.BundleVersion == nil {
		var ret string
		return ret
	}
	return *o.BundleVersion
}

// GetBundleVersionOk returns a tuple with the BundleVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetBundleVersionOk() (*string, bool) {
	if o == nil || o.BundleVersion == nil {
		return nil, false
	}
	return o.BundleVersion, true
}

// HasBundleVersion returns a boolean if a field has been set.
func (o *GetBrandingRes) HasBundleVersion() bool {
	if o != nil && o.BundleVersion != nil {
		return true
	}

	return false
}

// SetBundleVersion gets a reference to the given string and assigns it to the BundleVersion field.
func (o *GetBrandingRes) SetBundleVersion(v string) {
	o.BundleVersion = &v
}

// GetCustomOpenIdAppClazz returns the CustomOpenIdAppClazz field value if set, zero value otherwise.
func (o *GetBrandingRes) GetCustomOpenIdAppClazz() string {
	if o == nil || o.CustomOpenIdAppClazz == nil {
		var ret string
		return ret
	}
	return *o.CustomOpenIdAppClazz
}

// GetCustomOpenIdAppClazzOk returns a tuple with the CustomOpenIdAppClazz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetCustomOpenIdAppClazzOk() (*string, bool) {
	if o == nil || o.CustomOpenIdAppClazz == nil {
		return nil, false
	}
	return o.CustomOpenIdAppClazz, true
}

// HasCustomOpenIdAppClazz returns a boolean if a field has been set.
func (o *GetBrandingRes) HasCustomOpenIdAppClazz() bool {
	if o != nil && o.CustomOpenIdAppClazz != nil {
		return true
	}

	return false
}

// SetCustomOpenIdAppClazz gets a reference to the given string and assigns it to the CustomOpenIdAppClazz field.
func (o *GetBrandingRes) SetCustomOpenIdAppClazz(v string) {
	o.CustomOpenIdAppClazz = &v
}

// GetCustomSsoAppClazz returns the CustomSsoAppClazz field value if set, zero value otherwise.
func (o *GetBrandingRes) GetCustomSsoAppClazz() string {
	if o == nil || o.CustomSsoAppClazz == nil {
		var ret string
		return ret
	}
	return *o.CustomSsoAppClazz
}

// GetCustomSsoAppClazzOk returns a tuple with the CustomSsoAppClazz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetCustomSsoAppClazzOk() (*string, bool) {
	if o == nil || o.CustomSsoAppClazz == nil {
		return nil, false
	}
	return o.CustomSsoAppClazz, true
}

// HasCustomSsoAppClazz returns a boolean if a field has been set.
func (o *GetBrandingRes) HasCustomSsoAppClazz() bool {
	if o != nil && o.CustomSsoAppClazz != nil {
		return true
	}

	return false
}

// SetCustomSsoAppClazz gets a reference to the given string and assigns it to the CustomSsoAppClazz field.
func (o *GetBrandingRes) SetCustomSsoAppClazz(v string) {
	o.CustomSsoAppClazz = &v
}

// GetCustomSsoIdPAppClazz returns the CustomSsoIdPAppClazz field value if set, zero value otherwise.
func (o *GetBrandingRes) GetCustomSsoIdPAppClazz() string {
	if o == nil || o.CustomSsoIdPAppClazz == nil {
		var ret string
		return ret
	}
	return *o.CustomSsoIdPAppClazz
}

// GetCustomSsoIdPAppClazzOk returns a tuple with the CustomSsoIdPAppClazz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetCustomSsoIdPAppClazzOk() (*string, bool) {
	if o == nil || o.CustomSsoIdPAppClazz == nil {
		return nil, false
	}
	return o.CustomSsoIdPAppClazz, true
}

// HasCustomSsoIdPAppClazz returns a boolean if a field has been set.
func (o *GetBrandingRes) HasCustomSsoIdPAppClazz() bool {
	if o != nil && o.CustomSsoIdPAppClazz != nil {
		return true
	}

	return false
}

// SetCustomSsoIdPAppClazz gets a reference to the given string and assigns it to the CustomSsoIdPAppClazz field.
func (o *GetBrandingRes) SetCustomSsoIdPAppClazz(v string) {
	o.CustomSsoIdPAppClazz = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetBrandingRes) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetBrandingRes) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetBrandingRes) SetDescription(v string) {
	o.Description = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetBrandingRes) GetError() string {
	if o == nil || o.Error == nil {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetErrorOk() (*string, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetBrandingRes) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetBrandingRes) SetError(v string) {
	o.Error = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetBrandingRes) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetBrandingRes) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetBrandingRes) SetName(v string) {
	o.Name = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *GetBrandingRes) GetResource() string {
	if o == nil || o.Resource == nil {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetResourceOk() (*string, bool) {
	if o == nil || o.Resource == nil {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *GetBrandingRes) HasResource() bool {
	if o != nil && o.Resource != nil {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *GetBrandingRes) SetResource(v string) {
	o.Resource = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetBrandingRes) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBrandingRes) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetBrandingRes) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetBrandingRes) SetType(v string) {
	o.Type = &v
}

func (o GetBrandingRes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BundleArtifact != nil {
		toSerialize["bundleArtifact"] = o.BundleArtifact
	}
	if o.BundleGroup != nil {
		toSerialize["bundleGroup"] = o.BundleGroup
	}
	if o.BundleVersion != nil {
		toSerialize["bundleVersion"] = o.BundleVersion
	}
	if o.CustomOpenIdAppClazz != nil {
		toSerialize["customOpenIdAppClazz"] = o.CustomOpenIdAppClazz
	}
	if o.CustomSsoAppClazz != nil {
		toSerialize["customSsoAppClazz"] = o.CustomSsoAppClazz
	}
	if o.CustomSsoIdPAppClazz != nil {
		toSerialize["customSsoIdPAppClazz"] = o.CustomSsoIdPAppClazz
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Resource != nil {
		toSerialize["resource"] = o.Resource
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *GetBrandingRes) UnmarshalJSON(bytes []byte) (err error) {
	varGetBrandingRes := _GetBrandingRes{}

	if err = json.Unmarshal(bytes, &varGetBrandingRes); err == nil {
		*o = GetBrandingRes(varGetBrandingRes)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "bundleArtifact")
		delete(additionalProperties, "bundleGroup")
		delete(additionalProperties, "bundleVersion")
		delete(additionalProperties, "customOpenIdAppClazz")
		delete(additionalProperties, "customSsoAppClazz")
		delete(additionalProperties, "customSsoIdPAppClazz")
		delete(additionalProperties, "description")
		delete(additionalProperties, "error")
		delete(additionalProperties, "name")
		delete(additionalProperties, "resource")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetBrandingRes struct {
	value *GetBrandingRes
	isSet bool
}

func (v NullableGetBrandingRes) Get() *GetBrandingRes {
	return v.value
}

func (v *NullableGetBrandingRes) Set(val *GetBrandingRes) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBrandingRes) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBrandingRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBrandingRes(val *GetBrandingRes) *NullableGetBrandingRes {
	return &NullableGetBrandingRes{value: val, isSet: true}
}

func (v NullableGetBrandingRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBrandingRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


