/*
 * Atricore Console :: Remote : API
 *
 * # Atricore Console API
 *
 * API version: 1.4.3-SNAPSHOT
 * Contact: sgonzalez@atricore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// CreateIdPReq struct for CreateIdPReq
type CreateIdPReq struct {
	Config *SamlR2IDPConfigDTO `json:"config,omitempty"`
	IdaName *string `json:"idaName,omitempty"`
	Idp *IdentityProviderDTO `json:"idp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateIdPReq CreateIdPReq

// NewCreateIdPReq instantiates a new CreateIdPReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIdPReq() *CreateIdPReq {
	this := CreateIdPReq{}
	return &this
}

// NewCreateIdPReqWithDefaults instantiates a new CreateIdPReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIdPReqWithDefaults() *CreateIdPReq {
	this := CreateIdPReq{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *CreateIdPReq) GetConfig() SamlR2IDPConfigDTO {
	if o == nil || o.Config == nil {
		var ret SamlR2IDPConfigDTO
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdPReq) GetConfigOk() (*SamlR2IDPConfigDTO, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *CreateIdPReq) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given SamlR2IDPConfigDTO and assigns it to the Config field.
func (o *CreateIdPReq) SetConfig(v SamlR2IDPConfigDTO) {
	o.Config = &v
}

// GetIdaName returns the IdaName field value if set, zero value otherwise.
func (o *CreateIdPReq) GetIdaName() string {
	if o == nil || o.IdaName == nil {
		var ret string
		return ret
	}
	return *o.IdaName
}

// GetIdaNameOk returns a tuple with the IdaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdPReq) GetIdaNameOk() (*string, bool) {
	if o == nil || o.IdaName == nil {
		return nil, false
	}
	return o.IdaName, true
}

// HasIdaName returns a boolean if a field has been set.
func (o *CreateIdPReq) HasIdaName() bool {
	if o != nil && o.IdaName != nil {
		return true
	}

	return false
}

// SetIdaName gets a reference to the given string and assigns it to the IdaName field.
func (o *CreateIdPReq) SetIdaName(v string) {
	o.IdaName = &v
}

// GetIdp returns the Idp field value if set, zero value otherwise.
func (o *CreateIdPReq) GetIdp() IdentityProviderDTO {
	if o == nil || o.Idp == nil {
		var ret IdentityProviderDTO
		return ret
	}
	return *o.Idp
}

// GetIdpOk returns a tuple with the Idp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdPReq) GetIdpOk() (*IdentityProviderDTO, bool) {
	if o == nil || o.Idp == nil {
		return nil, false
	}
	return o.Idp, true
}

// HasIdp returns a boolean if a field has been set.
func (o *CreateIdPReq) HasIdp() bool {
	if o != nil && o.Idp != nil {
		return true
	}

	return false
}

// SetIdp gets a reference to the given IdentityProviderDTO and assigns it to the Idp field.
func (o *CreateIdPReq) SetIdp(v IdentityProviderDTO) {
	o.Idp = &v
}

func (o CreateIdPReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	if o.IdaName != nil {
		toSerialize["idaName"] = o.IdaName
	}
	if o.Idp != nil {
		toSerialize["idp"] = o.Idp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CreateIdPReq) UnmarshalJSON(bytes []byte) (err error) {
	varCreateIdPReq := _CreateIdPReq{}

	if err = json.Unmarshal(bytes, &varCreateIdPReq); err == nil {
		*o = CreateIdPReq(varCreateIdPReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "config")
		delete(additionalProperties, "idaName")
		delete(additionalProperties, "idp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateIdPReq struct {
	value *CreateIdPReq
	isSet bool
}

func (v NullableCreateIdPReq) Get() *CreateIdPReq {
	return v.value
}

func (v *NullableCreateIdPReq) Set(val *CreateIdPReq) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIdPReq) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIdPReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIdPReq(val *CreateIdPReq) *NullableCreateIdPReq {
	return &NullableCreateIdPReq{value: val, isSet: true}
}

func (v NullableCreateIdPReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIdPReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


