/*
Atricore Console :: Remote : API

# Atricore Console API

API version: 1.5.0-SNAPSHOT
Contact: sgonzalez@atricore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// BuiltInAttributeProfileDTO struct for BuiltInAttributeProfileDTO
type BuiltInAttributeProfileDTO struct {
	ElementId *string `json:"elementId,omitempty"`
	Id *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	ProfileType *string `json:"profileType,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BuiltInAttributeProfileDTO BuiltInAttributeProfileDTO

// NewBuiltInAttributeProfileDTO instantiates a new BuiltInAttributeProfileDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuiltInAttributeProfileDTO() *BuiltInAttributeProfileDTO {
	this := BuiltInAttributeProfileDTO{}
	return &this
}

// NewBuiltInAttributeProfileDTOWithDefaults instantiates a new BuiltInAttributeProfileDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuiltInAttributeProfileDTOWithDefaults() *BuiltInAttributeProfileDTO {
	this := BuiltInAttributeProfileDTO{}
	return &this
}

// GetElementId returns the ElementId field value if set, zero value otherwise.
func (o *BuiltInAttributeProfileDTO) GetElementId() string {
	if o == nil || o.ElementId == nil {
		var ret string
		return ret
	}
	return *o.ElementId
}

// GetElementIdOk returns a tuple with the ElementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuiltInAttributeProfileDTO) GetElementIdOk() (*string, bool) {
	if o == nil || o.ElementId == nil {
		return nil, false
	}
	return o.ElementId, true
}

// HasElementId returns a boolean if a field has been set.
func (o *BuiltInAttributeProfileDTO) HasElementId() bool {
	if o != nil && o.ElementId != nil {
		return true
	}

	return false
}

// SetElementId gets a reference to the given string and assigns it to the ElementId field.
func (o *BuiltInAttributeProfileDTO) SetElementId(v string) {
	o.ElementId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BuiltInAttributeProfileDTO) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuiltInAttributeProfileDTO) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BuiltInAttributeProfileDTO) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *BuiltInAttributeProfileDTO) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BuiltInAttributeProfileDTO) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuiltInAttributeProfileDTO) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BuiltInAttributeProfileDTO) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BuiltInAttributeProfileDTO) SetName(v string) {
	o.Name = &v
}

// GetProfileType returns the ProfileType field value if set, zero value otherwise.
func (o *BuiltInAttributeProfileDTO) GetProfileType() string {
	if o == nil || o.ProfileType == nil {
		var ret string
		return ret
	}
	return *o.ProfileType
}

// GetProfileTypeOk returns a tuple with the ProfileType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuiltInAttributeProfileDTO) GetProfileTypeOk() (*string, bool) {
	if o == nil || o.ProfileType == nil {
		return nil, false
	}
	return o.ProfileType, true
}

// HasProfileType returns a boolean if a field has been set.
func (o *BuiltInAttributeProfileDTO) HasProfileType() bool {
	if o != nil && o.ProfileType != nil {
		return true
	}

	return false
}

// SetProfileType gets a reference to the given string and assigns it to the ProfileType field.
func (o *BuiltInAttributeProfileDTO) SetProfileType(v string) {
	o.ProfileType = &v
}

func (o BuiltInAttributeProfileDTO) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ElementId != nil {
		toSerialize["elementId"] = o.ElementId
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.ProfileType != nil {
		toSerialize["profileType"] = o.ProfileType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BuiltInAttributeProfileDTO) UnmarshalJSON(bytes []byte) (err error) {
	varBuiltInAttributeProfileDTO := _BuiltInAttributeProfileDTO{}

	if err = json.Unmarshal(bytes, &varBuiltInAttributeProfileDTO); err == nil {
		*o = BuiltInAttributeProfileDTO(varBuiltInAttributeProfileDTO)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "elementId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "profileType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBuiltInAttributeProfileDTO struct {
	value *BuiltInAttributeProfileDTO
	isSet bool
}

func (v NullableBuiltInAttributeProfileDTO) Get() *BuiltInAttributeProfileDTO {
	return v.value
}

func (v *NullableBuiltInAttributeProfileDTO) Set(val *BuiltInAttributeProfileDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableBuiltInAttributeProfileDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableBuiltInAttributeProfileDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuiltInAttributeProfileDTO(val *BuiltInAttributeProfileDTO) *NullableBuiltInAttributeProfileDTO {
	return &NullableBuiltInAttributeProfileDTO{value: val, isSet: true}
}

func (v NullableBuiltInAttributeProfileDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuiltInAttributeProfileDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


