/*
Atricore Console :: Remote : API

# Atricore Console API

API version: 1.5.0-SNAPSHOT
Contact: sgonzalez@atricore.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// StoreOidcRpReq struct for StoreOidcRpReq
type StoreOidcRpReq struct {
	IdaName *string `json:"idaName,omitempty"`
	OidcRp *ExternalOpenIDConnectRelayingPartyDTO `json:"oidcRp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StoreOidcRpReq StoreOidcRpReq

// NewStoreOidcRpReq instantiates a new StoreOidcRpReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreOidcRpReq() *StoreOidcRpReq {
	this := StoreOidcRpReq{}
	return &this
}

// NewStoreOidcRpReqWithDefaults instantiates a new StoreOidcRpReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreOidcRpReqWithDefaults() *StoreOidcRpReq {
	this := StoreOidcRpReq{}
	return &this
}

// GetIdaName returns the IdaName field value if set, zero value otherwise.
func (o *StoreOidcRpReq) GetIdaName() string {
	if o == nil || o.IdaName == nil {
		var ret string
		return ret
	}
	return *o.IdaName
}

// GetIdaNameOk returns a tuple with the IdaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreOidcRpReq) GetIdaNameOk() (*string, bool) {
	if o == nil || o.IdaName == nil {
		return nil, false
	}
	return o.IdaName, true
}

// HasIdaName returns a boolean if a field has been set.
func (o *StoreOidcRpReq) HasIdaName() bool {
	if o != nil && o.IdaName != nil {
		return true
	}

	return false
}

// SetIdaName gets a reference to the given string and assigns it to the IdaName field.
func (o *StoreOidcRpReq) SetIdaName(v string) {
	o.IdaName = &v
}

// GetOidcRp returns the OidcRp field value if set, zero value otherwise.
func (o *StoreOidcRpReq) GetOidcRp() ExternalOpenIDConnectRelayingPartyDTO {
	if o == nil || o.OidcRp == nil {
		var ret ExternalOpenIDConnectRelayingPartyDTO
		return ret
	}
	return *o.OidcRp
}

// GetOidcRpOk returns a tuple with the OidcRp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StoreOidcRpReq) GetOidcRpOk() (*ExternalOpenIDConnectRelayingPartyDTO, bool) {
	if o == nil || o.OidcRp == nil {
		return nil, false
	}
	return o.OidcRp, true
}

// HasOidcRp returns a boolean if a field has been set.
func (o *StoreOidcRpReq) HasOidcRp() bool {
	if o != nil && o.OidcRp != nil {
		return true
	}

	return false
}

// SetOidcRp gets a reference to the given ExternalOpenIDConnectRelayingPartyDTO and assigns it to the OidcRp field.
func (o *StoreOidcRpReq) SetOidcRp(v ExternalOpenIDConnectRelayingPartyDTO) {
	o.OidcRp = &v
}

func (o StoreOidcRpReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IdaName != nil {
		toSerialize["idaName"] = o.IdaName
	}
	if o.OidcRp != nil {
		toSerialize["oidcRp"] = o.OidcRp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *StoreOidcRpReq) UnmarshalJSON(bytes []byte) (err error) {
	varStoreOidcRpReq := _StoreOidcRpReq{}

	if err = json.Unmarshal(bytes, &varStoreOidcRpReq); err == nil {
		*o = StoreOidcRpReq(varStoreOidcRpReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "idaName")
		delete(additionalProperties, "oidcRp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStoreOidcRpReq struct {
	value *StoreOidcRpReq
	isSet bool
}

func (v NullableStoreOidcRpReq) Get() *StoreOidcRpReq {
	return v.value
}

func (v *NullableStoreOidcRpReq) Set(val *StoreOidcRpReq) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreOidcRpReq) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreOidcRpReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreOidcRpReq(val *StoreOidcRpReq) *NullableStoreOidcRpReq {
	return &NullableStoreOidcRpReq{value: val, isSet: true}
}

func (v NullableStoreOidcRpReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreOidcRpReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


