/*
 * Atricore Console :: Remote : API
 *
 * # Atricore Console API
 *
 * API version: 1.4.3-SNAPSHOT
 * Contact: sgonzalez@atricore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// GetIdPsReq struct for GetIdPsReq
type GetIdPsReq struct {
	IdaName *string `json:"idaName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetIdPsReq GetIdPsReq

// NewGetIdPsReq instantiates a new GetIdPsReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIdPsReq() *GetIdPsReq {
	this := GetIdPsReq{}
	return &this
}

// NewGetIdPsReqWithDefaults instantiates a new GetIdPsReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIdPsReqWithDefaults() *GetIdPsReq {
	this := GetIdPsReq{}
	return &this
}

// GetIdaName returns the IdaName field value if set, zero value otherwise.
func (o *GetIdPsReq) GetIdaName() string {
	if o == nil || o.IdaName == nil {
		var ret string
		return ret
	}
	return *o.IdaName
}

// GetIdaNameOk returns a tuple with the IdaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIdPsReq) GetIdaNameOk() (*string, bool) {
	if o == nil || o.IdaName == nil {
		return nil, false
	}
	return o.IdaName, true
}

// HasIdaName returns a boolean if a field has been set.
func (o *GetIdPsReq) HasIdaName() bool {
	if o != nil && o.IdaName != nil {
		return true
	}

	return false
}

// SetIdaName gets a reference to the given string and assigns it to the IdaName field.
func (o *GetIdPsReq) SetIdaName(v string) {
	o.IdaName = &v
}

func (o GetIdPsReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IdaName != nil {
		toSerialize["idaName"] = o.IdaName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *GetIdPsReq) UnmarshalJSON(bytes []byte) (err error) {
	varGetIdPsReq := _GetIdPsReq{}

	if err = json.Unmarshal(bytes, &varGetIdPsReq); err == nil {
		*o = GetIdPsReq(varGetIdPsReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "idaName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetIdPsReq struct {
	value *GetIdPsReq
	isSet bool
}

func (v NullableGetIdPsReq) Get() *GetIdPsReq {
	return v.value
}

func (v *NullableGetIdPsReq) Set(val *GetIdPsReq) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIdPsReq) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIdPsReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIdPsReq(val *GetIdPsReq) *NullableGetIdPsReq {
	return &NullableGetIdPsReq{value: val, isSet: true}
}

func (v NullableGetIdPsReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIdPsReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


