/*
 * Atricore Console :: Remote : API
 *
 * # Atricore Console API
 *
 * API version: 1.4.3-SNAPSHOT
 * Contact: sgonzalez@atricore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jossoappi

import (
	"encoding/json"
)

// DeleteIdPReq struct for DeleteIdPReq
type DeleteIdPReq struct {
	IdaName *string `json:"idaName,omitempty"`
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeleteIdPReq DeleteIdPReq

// NewDeleteIdPReq instantiates a new DeleteIdPReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteIdPReq() *DeleteIdPReq {
	this := DeleteIdPReq{}
	return &this
}

// NewDeleteIdPReqWithDefaults instantiates a new DeleteIdPReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteIdPReqWithDefaults() *DeleteIdPReq {
	this := DeleteIdPReq{}
	return &this
}

// GetIdaName returns the IdaName field value if set, zero value otherwise.
func (o *DeleteIdPReq) GetIdaName() string {
	if o == nil || o.IdaName == nil {
		var ret string
		return ret
	}
	return *o.IdaName
}

// GetIdaNameOk returns a tuple with the IdaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteIdPReq) GetIdaNameOk() (*string, bool) {
	if o == nil || o.IdaName == nil {
		return nil, false
	}
	return o.IdaName, true
}

// HasIdaName returns a boolean if a field has been set.
func (o *DeleteIdPReq) HasIdaName() bool {
	if o != nil && o.IdaName != nil {
		return true
	}

	return false
}

// SetIdaName gets a reference to the given string and assigns it to the IdaName field.
func (o *DeleteIdPReq) SetIdaName(v string) {
	o.IdaName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeleteIdPReq) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteIdPReq) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeleteIdPReq) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeleteIdPReq) SetName(v string) {
	o.Name = &v
}

func (o DeleteIdPReq) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IdaName != nil {
		toSerialize["idaName"] = o.IdaName
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *DeleteIdPReq) UnmarshalJSON(bytes []byte) (err error) {
	varDeleteIdPReq := _DeleteIdPReq{}

	if err = json.Unmarshal(bytes, &varDeleteIdPReq); err == nil {
		*o = DeleteIdPReq(varDeleteIdPReq)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "idaName")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeleteIdPReq struct {
	value *DeleteIdPReq
	isSet bool
}

func (v NullableDeleteIdPReq) Get() *DeleteIdPReq {
	return v.value
}

func (v *NullableDeleteIdPReq) Set(val *DeleteIdPReq) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteIdPReq) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteIdPReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteIdPReq(val *DeleteIdPReq) *NullableDeleteIdPReq {
	return &NullableDeleteIdPReq{value: val, isSet: true}
}

func (v NullableDeleteIdPReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteIdPReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


